name: main
# push files into docs-website repo
on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: qianqianluo/docs-website-original@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'rst/'
        destination_repo: 'tigase/docs-website'
        destination_folder: 'docs'
        user_email: 'qianqianluo@gmail.com'
        user_name: 'Qian Luo'
        commit_message: 'add new rst file'
    
